import { MetadataRoute } from 'next'
 
export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.taskey.de'
  
  return [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
    },
    {
      url: `${baseUrl}/was-ist-taskey`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/features`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/demo`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.95,
    },
    {
      url: `${baseUrl}/pricing`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/about`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/rollen`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/enterprise`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/impressum`,
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/partnerschaften`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/datenschutz`,
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: `${baseUrl}/agb`,
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    // Lösungen Übersichtsseite
    {
      url: `${baseUrl}/loesungen`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    // SEO Landing Pages - Lösungen
    ...[
      'zeiterfassung-handwerk',
      'zeiterfassung-baustelle',
      'stundennachweise-digital',
      'arbeitszeiterfassung-reinigungsfirma',
      'mitarbeiter-stunden-tracken-handwerk',
      'mobile-zeiterfassung-monteure',
      'zeiterfassung-app-aussendienst',
      'ueberstunden-verwalten-handwerksbetrieb',
      'schichtplanung-reinigungsunternehmen',
      'personalplanung-baufirma',
      'auftragsverwaltung-handwerk',
      'auftraege-organisieren-malerbetrieb',
      'bauprojekte-planen-software',
      'auftragsplanung-reinigungsfirma',
      'projektmanagement-kleine-baufirma',
      'auftragsuebesicht-handwerksbetrieb',
      'baustellen-koordinieren-tool',
      'auftraege-digital-verwalten-handwerk',
      'terminplanung-handwerker',
      'einsatzplanung-gebaeudereinigung',
      'angebote-schreiben-handwerk',
      'rechnungsprogramm-handwerker',
      'kundenverwaltung-handwerksbetrieb',
      'disposition-handwerk-software',
      'einsatzplanung-monteure',
      'rechnung-schreiben-reinigungsfirma',
      'angebotskalkulation-bau',
      'abschlagsrechnung-erstellen-handwerk',
      'schlussrechnung-software-bau',
      'aufmass-erstellen-digital',
      'rechnungen-nachverfolgen-handwerksbetrieb',
      'mahnwesen-handwerk',
      'kostenvoranschlag-erstellen-software',
      'bautagebuch-digital',
      'baudokumentation-software',
      'fotos-baustelle-dokumentieren-app',
      'rapportzettel-digital-handwerk',
      'abnahmeprotokoll-digital',
      'leistungsnachweis-gebaeudereinigung',
      'maengeldokumentation-bau',
      'bauakte-digital-erstellen',
      'uebergabeprotokoll-reinigung',
      'protokolle-baustelle-erstellen',
      'materialverwaltung-handwerk',
      'werkzeugverwaltung-handwerk',
      'lagerverwaltung-handwerksbetrieb',
      'materialliste-baustelle-erstellen',
      'bestellwesen-handwerksbetrieb',
      'materialverbrauch-tracken-baustelle',
      'inventar-verwalten-reinigungsfirma',
      'lieferscheine-digital-erstellen-handwerk',
      'buchhaltung-handwerksbetrieb',
      'nachkalkulation-handwerk',
      'gewinn-pro-auftrag-berechnen',
      'einnahmen-ausgaben-handwerker',
      'vorbereitung-steuerberater-handwerk',
      'liquiditaetsplanung-baufirma',
      'bauabrechnung-software',
      'stundensaetze-kalkulieren-handwerk',
      'lohnabrechnung-reinigungsfirma',
      'crm-fuer-handwerker',
      'kundendatenbank-reinigungsfirma',
      'kundenhistorie-verwalten-handwerk',
      'kundenkommunikation-baufirma',
      'reklamationen-verwalten-handwerk',
      'kundenfeedback-reinigung',
      'stammkunden-verwalten-gebaeudereinigung',
      'mitarbeiter-auf-baustellen-einteilen',
      'fahrzeugplanung-handwerksbetrieb',
      'ressourcenplanung-baufirma',
      'kolonnenplanung-bau',
      'kapazitaetsplanung-handwerk',
      'tagesplanung-reinigungskraefte',
      'wochenplan-handwerker-erstellen',
      'digitalisierung-handwerksbetrieb',
      'handwerker-app-baustelle',
      'papierloses-buero-handwerk',
      'handwerk-software-einfach',
      'app-fuer-handwerker-aussendienst',
      'bueroarbeit-reduzieren-handwerk',
      'zettelwirtschaft-abschaffen-handwerk',
      'alles-in-einer-app-handwerksbetrieb',
      'subunternehmer-verwalten-bau',
      'nachunternehmer-koordinieren-software',
      'fremdleistungen-abrechnen-bau',
      'subunternehmer-einsatzplanung',
      'nachunternehmer-dokumentation',
      'checklisten-reinigung-digital',
      'wartungschecklisten-handwerk',
      'sicherheitschecklisten-baustelle',
      'reinigungsplaene-digital-erstellen',
      'objektbegehung-reinigung-dokumentieren',
      'sla-tracking-reinigungsfirma',
      'team-kommunikation-baustelle',
      'chat-app-handwerksbetrieb',
      'infos-an-monteure-senden',
      'baustelleninfos-teilen-app',
      'krankmeldung-digital-handwerk',
      'qualitaetskontrolle-gebaeudereinigung',
      'tourenplanung-reinigungsteams',
      'digitale-unterschrift-bauabnahme',
    ].map((slug) => ({
      url: `${baseUrl}/loesungen/${slug}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
  ]
}
